title:        Chris Palmer
tagline:      'Why hello, there!'
description:  "Cofounder at Minerva Foundry. Engineering Chemistry grad. Coding novice. Learning enthusiast. Would love to meet you."
url:          http://cwjpalmer.com
version:      1.1.1
author:
  name:       'Chris Palmer'
  email:      'cwjpalmer@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
