title:        cwjpalmer.com
tagline:      'Why hello, there!'
description:  "Thanks for checking out my website."
url:          http://cwjpalmer.com
version:      1.1.1
author:
  name:       'Chris Palmer'
  email:      'cwjpalmer@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
